/*
-- Query: SELECT * FROM forex_db.currencies
LIMIT 0, 1000

-- Date: 2025-09-02 00:41
*/
INSERT INTO forex_db.currencies (code, name) VALUES
('USD', 'US Dollar'),
('EUR', 'Euro'),
('GBP', 'British Pound'),
('JPY', 'Japanese Yen'),
('AUD', 'Australian Dollar'),
('CAD', 'Canadian Dollar'),
('CHF', 'Swiss Franc'),
('CNY', 'Chinese Yuan'),
('HKD', 'Hong Kong Dollar'),
('SGD', 'Singapore Dollar'),
('NZD', 'New Zealand Dollar'),
('SEK', 'Swedish Krona'),
('NOK', 'Norwegian Krone'),
('DKK', 'Danish Krone'),
('KRW', 'South Korean Won'),
('INR', 'Indian Rupee'),
('BRL', 'Brazilian Real'),
('MXN', 'Mexican Peso'),
('ZAR', 'South African Rand'),
('TRY', 'Turkish Lira'),
('MYR', 'Malaysian Ringgit'),
('THB', 'Thai Baht'),
('PHP', 'Philippine Peso'),
('TWD', 'New Taiwan Dollar'),
('HUF', 'Hungarian Forint'),
('ARS', 'Argentine Peso'),
('CLP', 'Chilean Peso'),
('COP', 'Colombian Peso'),
('CZK', 'Czech Koruna'),
('EGP', 'Egyptian Pound'),
('IDR', 'Indonesian Rupiah'),
('ILS', 'Israeli Shekel'),
('JOD', 'Jordanian Dinar'),
('KWD', 'Kuwaiti Dinar'),
('LKR', 'Sri Lankan Rupee'),
('MAD', 'Moroccan Dirham'),
('NGN', 'Nigerian Naira'),
('OMR', 'Omani Rial'),
('PKR', 'Pakistani Rupee'),
('QAR', 'Qatari Riyal'),
('RON', 'Romanian Leu'),
('RUB', 'Russian Ruble'),
('SAR', 'Saudi Riyal'),
('VND', 'Vietnamese Dong'),
('UAH', 'Ukrainian Hryvnia'),
('BDT', 'Bangladeshi Taka'),
('BHD', 'Bahraini Dinar'),
('ISK', 'Icelandic Krona');
